// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('0 Amount', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('0 Amount', async function() {
    await driver.get("https://beyondblue--dev.lightning.force.com/lightning/r/Contact/0030l00000UedkOAAR/view?0.source=alohaHeader")
    await driver.findElement(By.css(".slds-button:nth-child(1) > .forceActionLink > .slds-truncate")).click()
    await driver.findElement(By.xpath("//lightning-input/div/input")).sendKeys("0")
    await driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/div/input")).click()
    await driver.findElement(By.css(".slds-lookup__list:nth-child(2) > li:nth-child(1) > .slds-lookup__item-action")).click()
    await driver.findElement(By.xpath("//div[4]/div[2]/div/lightning-input/div/input")).click()
    await driver.findElement(By.xpath("//div[4]/div[2]/div/lightning-input/div/input")).sendKeys("4444333322221111")
    await driver.findElement(By.xpath("//div[3]/div/lightning-input/div/input")).click()
    await driver.findElement(By.xpath("//div[3]/div/lightning-input/div/input")).sendKeys("ddd")
    await driver.findElement(By.xpath("//select")).click()
    {
      const dropdown = await driver.findElement(By.xpath("//select"))
      await dropdown.findElement(By.css("*:nth-child(2)")).click()
    }
    await driver.findElement(By.xpath("//div[2]/div/div/div/select")).click()
    {
      const dropdown = await driver.findElement(By.xpath("//div[2]/div/div/div/select"))
      await dropdown.findElement(By.css("*:nth-child(5)")).click()
    }
    await driver.findElement(By.xpath("//div[3]/lightning-input/div/input")).click()
    await driver.findElement(By.xpath("//div[3]/lightning-input/div/input")).sendKeys("123")
    await driver.findElement(By.css(".slds-button_brand")).click()
    assert(await driver.findElement(By.css(".pageLevelErrors .genericNotification")).getText() == "Errors:")
  })
})
